import {
  ADD_USER_SCREEN,
  BRANCH_DETAIL_SCREEN,
  BRANCH_SCREEN,
  CHANGE_PASSWORD_SCREEN,
  DASHBOARD_SCREEN,
  EDIT_PROFILE_SCREEN,
  HOME_SCREEN,
  INFORMATION_SCREEN,
  LANDING_PAGE,
  LOGIN_SCREEN,
  MESSAGE_SCREEN,
  MY_BOOKING_SCREEN,
  STYLIST_SCREEN,
  NOTIFICATION_SCREEN,
  PERSONAL_SCREEN,
  PROFILE_SCREEN,
  REGISTER_SCREEN,
  SERVICE_DETAIL_SCREEN,
  SERVICE_MANAGER_SCREEN,
  SERVICE_SCREEN,
  USER_MANAGER_SCREEN,
  VERIFY_PHONE_SCREEN,
  CALENDAR_SCREEN,
  BRANCH_MANAGER_SCREEN,
  CREATE_BOOKING_SCREEN,
  BOOKING_DETAIL_SCREEN,
  SELECT_PAYMENT_SCREEN,
  PREVIEW_RATING_SCREEN,
  ADD_SERVICE_SCREEN,
  ADD_BRANCH_SCREEN,
} from '../constants/screen_key';

export type AuthStackParamList = {
  [LANDING_PAGE]: undefined;
  [LOGIN_SCREEN]: undefined;
  [VERIFY_PHONE_SCREEN]: undefined;
  [REGISTER_SCREEN]: undefined;
  [INFORMATION_SCREEN]: undefined;
};

export type MainStackParamList = {
  [HOME_SCREEN]: undefined;
  [SERVICE_SCREEN]: undefined;
  [MY_BOOKING_SCREEN]: undefined;
  [PERSONAL_SCREEN]: undefined;
  [PROFILE_SCREEN]: undefined;
  [EDIT_PROFILE_SCREEN]: undefined;
  [SERVICE_DETAIL_SCREEN]: undefined;
  [BRANCH_SCREEN]: undefined;
  [NOTIFICATION_SCREEN]: undefined;
  [STYLIST_SCREEN]: undefined;
  [BRANCH_DETAIL_SCREEN]: undefined;
  [CALENDAR_SCREEN]: undefined;
  [CREATE_BOOKING_SCREEN]: undefined;
  [BOOKING_DETAIL_SCREEN]: undefined;
  [SELECT_PAYMENT_SCREEN]: undefined;
  [CHANGE_PASSWORD_SCREEN]: undefined;
  [PREVIEW_RATING_SCREEN]: undefined;
};

export type AdminStackParamList = {
  [DASHBOARD_SCREEN]: undefined;
  [USER_MANAGER_SCREEN]: undefined;
  [SERVICE_MANAGER_SCREEN]: undefined;
  [PROFILE_SCREEN]: undefined;
  [EDIT_PROFILE_SCREEN]: undefined;
  [ADD_USER_SCREEN]: undefined;
  [BRANCH_MANAGER_SCREEN]: undefined;
  [ADD_SERVICE_SCREEN]: undefined;
  [ADD_BRANCH_SCREEN]: undefined;
};
